### ISSUE TITLE
setup problems

### ISSUE THREAD

**Issue by a-mahr** [sergiocorreia/quipucamayoc#1]
Hi there,
I'm trying to follow the setup instructions, and come across the following problems:
Following either set of instructions (pip or git), I end up at:
git:
-setup.py file is missing, none of other files seem to have the expected setup stuff under a different name
pip3:
quipu install aws
command not found: quipu
I'm not certain the pip3 problem isn't a path issue of my own, but I believe there are missing files necessary for the git installation

**Comment by sergiocorreia** [comment]
Hi,

Agree, the quipu.py file is missing on the install, should be an easy fix. Quick question: are you on Linux or Windows? (I have been testing on Win but can prioritize adding CI checks for Linux)

**Comment by a-mahr** [comment]
Hi, Thank you!
I'm primarily using Mac, and have access to Linux, I should be able to run anything released for Linux.

**Comment by sergiocorreia** [comment]
I just pushed an update that should work independently of the OS.

First, you need to install the [AWS CLI](https://aws.amazon.com/cli/) and run `aws configure` where you input your AWS credentials as explained in that page (this step should be easy to automate in the near future).

Once that is done, and you have `quipucamayoc updated to 0.1.2, running `quipu aws install` should do the trick.

Then, to extract tables from a PDF you can do `quipu extract-tables somefile.pdf`

I'm currently setting the output of the above commands to be very verbose (easier for debugging) but will also tune the verbosity down once we know it works in most setups. Some sample screenshots of how it should look:

![image](https://user-images.githubusercontent.com/214056/162890395-f1e8f291-557d-4bcd-8ded-2a25f31e78dc.png)

(Note: you can share your Key ID and username, but never share your Secret Access Key)

![image](https://user-images.githubusercontent.com/214056/162891096-a9645fc4-dcd3-4e5f-a029-82d2a61d0d44.png)

Here, how long you have to wait is a bit random and depends on how congested AWS currently is (can be 1 minute, can be 10).

**Comment by a-mahr** [comment]
Great, thank you!

**Comment by sergiocorreia** [comment]
Also, let me know if you have any questions or notice any pain points. We've tested this feature a lot internally but there are probably a lot of corner cases we haven't seen (e.g. if you don't have a credit card tied to your amazon account, then you might get an error when running an AWS job).
